package interface_adapter.playlist_genresplit;

import use_case.playlist_genresplit.PlaylistGenresplitOutputBoundary;

public class PlaylistGenresplitPresenter implements PlaylistGenresplitOutputBoundary {
}
