package interface_adapter.complete_yearsplit;

import use_case.complete_yearsplit.CompleteYearSplitOutputBoundary;

public class CompleteYearSplitPresenter implements CompleteYearSplitOutputBoundary {
}
